# Generated by Django 5.0.6 on 2024-06-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_invitation_date_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('max_projects_per_team', models.ImageField(default=0, upload_to='')),
                ('max_members_per_team', models.ImageField(default=0, upload_to='')),
                ('max_tasks_per_project', models.ImageField(default=0, upload_to='')),
                ('price', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
