# Generated by Django 5.0.6 on 2024-06-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='max_members_per_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_projects_per_team',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_tasks_per_project',
            field=models.IntegerField(default=0),
        ),
    ]
